### ISSUE TITLE
nil pointer panic

### ISSUE THREAD

**Issue by Jonwing** [Jonwing/mario#1]
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1222992]

goroutine 34 [running]:

golang.org/x/crypto/ssh.(*Client).dial(0x0, 0xc00002a7b0, 0x7, 0x0, 0xc00002a1f0, 0x9, 0x6989, 0x0, 0xc0009bcf10, 0xc00025c1e0, ...)

	/Users/lazur/Go/pkg/mod/golang.org/x/crypto@v0.0.0-20181203042331-505ab145d0a9/ssh/tcpip.go:422 +0x152

golang.org/x/crypto/ssh.(*Client).Dial(0x0, 0x146624e, 0x3, 0xc00002a1f0, 0xf, 0xc0000b6180, 0xc0009bef68, 0x100700b, 0xc0000b6180)

	/Users/lazur/Go/pkg/mod/golang.org/x/crypto@v0.0.0-20181203042331-505ab145d0a9/ssh/tcpip.go:350 +0x168

github.com/Jonwing/mario/pkg/ssh.(*Tunnel).listenLocal.func1(0xc0000b6180, 0xc0009befb0)

	/Users/lazur/Go/src/github.com/Jonwing/mario/pkg/ssh/tunnel.go:209 +0x70

github.com/Jonwing/mario/pkg/ssh.(*Tunnel).Up(0xc00025e000)

	/Users/lazur/Go/src/github.com/Jonwing/mario/pkg/ssh/tunnel.go:188 +0x91

created by github.com/Jonwing/mario/internal.(*Mario).Establish

	/Users/lazur/Go/src/github.com/Jonwing/mario/internal/manage.go:187 +0x299

**Comment by Jonwing** [comment]
![image](https://user-images.githubusercontent.com/10095468/66582302-2346e480-ebb4-11e9-9034-1d699143391a.png)
